---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    code_folding: hide
    theme: journal
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(lubridate)

library(flexdashboard)
```

```{r, include = F}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>%
  filter(
    cuisine_description == "Chinese",
    grade == c("A", "B", "C")
  ) %>%
  mutate(inspection_date = as_date(inspection_date))

rest_inspec
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A


```{r}
rest_inspec %>%
  mutate(boro = fct_reorder(boro, score)) %>%
  plot_ly(
    y = ~score, x = ~boro, color = ~boro, 
    type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = "Area in NYC"),
    yaxis = list(title = "Score"),
    title = "Area in NYC vs. Score"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B


```{r}
rest_inspec %>%
  mutate(text_label = str_c("Grade: ", grade, "\nResturants: ", dba)) %>%
  plot_ly(
    x = ~inspection_date, y = ~score, color = ~boro, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers") %>% 
  layout(
    xaxis = list(title = "Inspection Date"),
    yaxis = list(title = "Score"),
    title = "Inspection Date vs. Score"
  )
```


### Chart C

```{r}
rest_inspec %>%
  distinct(dba, boro) %>% 
  count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(
    x = ~boro, y = ~n, color = ~boro, 
    type = "bar", colors = "viridis") %>%
   layout(
    xaxis = list(title = "Area in NYC"),
    yaxis = list(title = "Count"),
    title = "Area in NYC vs. Count"
  )
```
